### ISSUE TITLE
Can't make it works

### ISSUE THREAD

**Issue by kyrylo93** [DaPotatoMan/vue-next-masonry#3]
Hi, thank You for your work.
I tried to do the same, then I tried to use your package, and I can't say that It works.

Can i ask you to put demo on jsfiddle?

```
---App file---
import masonry from 'vue-next-masonry'
app.use(masonry)

---the code in vue file---
   <masonry :cols="3" :gutter="30">
      <div>1</div>
      <div>2</div>
      <div>3</div>
    </masonry>
```

**Comment by DaPotatoMan** [comment]
@kyrylo93
I have created a working example here https://codesandbox.io/s/vue-next-masonry-0kwxd
