### ISSUE TITLE
Trouble Working Inside Component With A Slot

### ISSUE THREAD

**Issue by dalezak** [DaPotatoMan/vue-next-masonry#4]
Everything seems to work fine when I use `masonry` component directly, however things don't seem to work when I use `masonry` inside a component that takes a `slot`, all the items are loaded in a single column.

For example, I have a reusable `grid-cards` component with a loading indicator, load more button, search bar, etc. 

```
<grid-cards v-model:search="search" :loading="loading" :onMore="onMore">
  <resource-card :resource="resource" :key="resource.id" v-for="resource in resources"></resource-card>
</grid-cards>
```

Inside `grid-cards` component I use `masonry` like the following:

```
<masonry :cols="{default: 4, 1140: 3, 720: 2, 400: 1}" :gutter="{default: '30px', 700: '15px'}">
  <slot></slot>
</masonry>
```

Any idea why `masonry` is not working when used with a `slot`? Do I need to somehow call `render` directly inside my components `updated`?

**Comment by DaPotatoMan** [comment]
@dalezak Thanks for reporting this. I have added a fix for this in the new version.

When using `<slot/>` use the prop `:resolve-slot="true"`. This will load child items from the slot.

```HTML
<masonry :resolve-slot="true">
   <slot />
</masonry>
```

Let me know if you are still facing any issues.

**Comment by dalezak** [comment]
Amazing, thank you @DaPotatoMan! I just tested it but getting `Cannot find module 'vue-next-masonry'`, although I can see it in `node_modules`. Any ideas?

<img width="159" alt="Screen Shot 2021-07-25 at 9 10 17 AM" src="https://user-images.githubusercontent.com/91811/126903997-6494e223-3a21-4095-952f-588f2b4e44dc.png">

**Comment by dalezak** [comment]
I noticed that version `1.0.4` only published the packaged code, could that be the problem with `1.1.0`?

<img width="144" alt="Screen Shot 2021-07-25 at 9 17 49 AM" src="https://user-images.githubusercontent.com/91811/126904244-aca656e1-0b3c-4be5-b540-c8d12f081243.png">

**Comment by DaPotatoMan** [comment]
Yeah, `1.1.0` was published incorrectly. It's fixed with version `1.1.1`

**Comment by dalezak** [comment]
Amazing, thanks for the fast turnaround @DaPotatoMan! The version `1.1.1` loads for me, however the cards still are not positioned in columns, but in the new version `1.1.2` the columns load great! Thanks again! 🙏

**Comment by dalezak** [comment]
@DaPotatoMan everything is working great in `1.1.3`, however on one page all the cards are still loaded in one column. The code is very similar to other pages so can't figure why it's happening. Do you have any insights or suggestions how we can fix this?

Here's how we're configuring `masonry` in our component.
```
<masonry :resolve-slot="true" :cols="{ default: 4, 1200: 3, 900: 2, 600: 1 }" :gutter="{ default: '20px' }">
  <slot></slot>
</masonry>
```

**Comment by dalezak** [comment]
_Found the problem!_ It was being caused due to Vue leaving an empty `v-if` comment in the source, which was likely causing problem when calculating columns. This is what our page looked like that wasn't working.

```
<grid-cards :loading="loading">
  <template v-if="surveys && surveys.length > 0">
    <survey-card :survey="survey" :key="survey.id" v-for="survey in surveys"></survey-card>
  </template>
  <template v-if="toolkits && toolkits.length > 0">
    <toolkit-card :toolkit="toolkit" :key="toolkit.id" v-for="toolkit in toolkits"></toolkit-card>
  </template>
</grid-cards>
```

And here's what source ended up looking like.

<img width="393" alt="screen_shot_2021-07-25_at_2 10 57_pm" src="https://user-images.githubusercontent.com/91811/126912652-b6140914-fe64-4137-a233-cb8c330af445.png">

I removed the `<template>` tags and instead combines all items into a single array.

```
<grid-cards :loading="loading">
  <template :key="card.id" v-for="card of cards">
    <survey-card :survey="card" v-if="card.type=='Survey'"></survey-card>
    <toolkit-card :toolkit="card" v-else-if="card.type=='Toolkit'"></toolkit-card>
  </template>
</grid-cards>
```

_And it works!_ So perhaps when positioning elements, you'll need to exclude `<!--v-if-->` from the algorithm.
